version: '3'
services:
  schema-extractor:
    build: .
    container_name: schema-extractor
    ports:
      - "8081:8080"
    networks:
      - n8n_default 
    restart: unless-stopped

networks:
  n8n_default:
    external: true 
